In [4]:
import numpy as np

In [5]:
My_list=[1,2,3,4,5]
My_list

[1, 2, 3, 4, 5]

In [6]:
np.array(My_list)

array([1, 2, 3, 4, 5])

# Matrix

In [7]:
my_matrix=([1,2,3],[4,5,6],[7,8,9])
my_matrix

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Arange

In [9]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
np.arange(2,22,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [12]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

# Zeros and Ones

In [13]:
np.zeros(2)

array([0., 0.])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Eye

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random

In [17]:
np.random.rand(5,5)

array([[0.58160108, 0.1936178 , 0.77442261, 0.27419704, 0.38515253],
       [0.38594493, 0.26318694, 0.02806577, 0.59942798, 0.93207859],
       [0.51340428, 0.81301217, 0.61693148, 0.24751685, 0.81493878],
       [0.60479762, 0.32774004, 0.67115605, 0.52229185, 0.94434505],
       [0.63224728, 0.66690018, 0.11832733, 0.6796835 , 0.19241852]])

In [18]:
np.random.randn(2,3)

array([[-0.62120166, -1.29804488,  0.38888178],
       [ 0.74970159, -0.28661783,  0.55964698]])

# Array attribute

In [19]:
np.arange(30)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
arr=np.arange(10,30,5)
arr

array([10, 15, 20, 25])

# Reshape

In [21]:
arr.reshape(2,2)

array([[10, 15],
       [20, 25]])

In [22]:
arr

array([10, 15, 20, 25])

In [23]:
arr.min()

10

In [24]:
arr.max()

25

In [25]:
arr.argmax()

3

In [26]:
arr.argmin()

0

In [27]:
arr

array([10, 15, 20, 25])

# Reshape

In [28]:
x=arr.reshape(2,2)
x

array([[10, 15],
       [20, 25]])

# Min and Max

In [29]:
x.min()

10

In [30]:
x.max()

25

# Dtype

In [31]:
x.dtype

dtype('int32')

# Linspace

In [32]:
np.linspace(1,20,7)

array([ 1.        ,  4.16666667,  7.33333333, 10.5       , 13.66666667,
       16.83333333, 20.        ])

In [33]:
np.linspace(5,20,4)

array([ 5., 10., 15., 20.])

In [34]:
np.random.randn(2,2)

array([[ 0.81918245,  0.66586979],
       [ 0.05947577, -1.60355868]])