###Numpy

In [2]:
import numpy as np

Numpy Arrays

In [3]:
#Creating the Array

##From a Python List
* We can create an array by directly converting a list or list of lists.

In [4]:
My_list=[1,2,3,4,5]
My_list

[1, 2, 3, 4, 5]

In [5]:
np.array(My_list)

array([1, 2, 3, 4, 5])

In [6]:
my_matrix=[[1,2,3],[4,5,6],[3,5,7]]

In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [3, 5, 7]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [3, 5, 7]])

# Built-in Methods
There are lots of built-in ways to generate Arrays

arrange

Return evenly spaced values within a given interval.

In [9]:
#It's same as range python
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

# zeros and ones
Generate arrays of zeros or ones

In [11]:
np.zeros(25)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(25)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
#5X5 matrix

np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# eye

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random

Numpy also has lots of ways to create random number arrays;

# rand 
Create an array of the given shape and populate it with random samples from a uniform distribution over[0,1]

In [16]:
np.random.rand(4)

array([0.06172213, 0.98300621, 0.58537586, 0.42628251])

In [17]:
np.random.rand(5,5)

array([[0.38126326, 0.53883683, 0.66986796, 0.74588171, 0.3994351 ],
       [0.59968921, 0.71812784, 0.93344479, 0.36744199, 0.18143107],
       [0.17742212, 0.22520744, 0.97654151, 0.60526067, 0.39757421],
       [0.628162  , 0.67375772, 0.17941277, 0.57255375, 0.71140737],
       [0.26710528, 0.36930415, 0.75192799, 0.79258133, 0.97158432]])

In [18]:
np.random.randn(5)

array([ 0.30912899, -0.4547581 ,  0.32414918,  0.59971777,  0.53705754])

In [22]:
np.random.randn(5,5)

array([[-0.68099406, -2.35340086,  1.72448993, -1.67657307, -0.77802396],
       [ 1.04816785, -1.46012971,  0.10364373, -0.7991998 ,  3.00935891],
       [-0.09862184, -0.1839069 , -2.04909373, -0.52667684,  0.19908525],
       [-0.62738922,  0.59328306, -0.40057615,  0.66385986,  0.27391692],
       [ 0.33491035,  2.47225161,  0.62426228,  0.08146097, -1.02634632]])

# randint1

#### Return random integers from 'low'(inclusive) to 'high'(exclusive)

In [24]:
np.random.randint(0,100)

56

In [27]:
np.random.randint(1,100,10)

array([47, 68, 14, 28, 42, 28, 21, 98, 87, 29])

# Array Attributes and Methods
Let's discuss some useful attributes and methods or an array.

In [28]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr=np.random.randint(0,50,10)
ranarr

array([39, 22, 47, 46, 26, 44,  8,  0,  8, 11])

# Reshape

In [30]:
#returns an array containing the same data with a new shape

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
# max,min,argmax,argmin
#These are useful methods for finding max or min values.Or to find their index locations using argmin or argmax

In [33]:
ranarr

array([39, 22, 47, 46, 26, 44,  8,  0,  8, 11])

In [34]:
ranarr.min()

0

In [36]:
ranarr.max()

47

In [37]:
# location of the max number / key
ranarr.argmax()

2

In [38]:
ranarr.argmin()

7

# Shape
Shape is an attribute that arrays have(not a method)

In [40]:
arr.shape

(25,)

In [41]:
arr.reshape(5,5).shape

(5, 5)

In [42]:
ok=arr.reshape(25,1)

In [43]:
ok.shape

(25, 1)

#### d type
You can also grab the data type of the object in the array;

In [44]:
arr.dtype

dtype('int32')

# Linspace

In [45]:
# Return evenly spaced numbers over a specified interval.

In [47]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [50]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])