In [1]:
# Numpy Indexing and Selection

#### here how to select elements or groups of elements from an array

In [3]:
import numpy as np

# creating sample array

In [4]:
arr=np.arange(0,11)

In [5]:
# show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similer to phython lists.

In [8]:
# Get a value at an index
arr[8]

8

In [9]:
# Get values in a range

arr[0:5]

array([0, 1, 2, 3, 4])

# Broadcasting

In [10]:
# Numpy arrays differ from a normal list because of their ability to broadcast:
arr[0:6]=100

# Setting a value with index range(Broadcasting)

arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Reset array,we'll see why I had to reset in a moment
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Slicing the elements

slice_of_arr=arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [17]:

#: means everything from strt to end 

slice_of_arr[:]=90
slice_of_arr

array([90, 90, 90, 90, 90])

# Data is not coppied,it's a view of the original array!This avoids memory problems!

In [19]:
arr_copy=arr.copy()

In [20]:
arr_copy

array([90, 90, 90, 90, 90,  5,  6,  7,  8,  9])

# Indexing a 2D array (matrics)
The original format is arr 2d[row][col]or arr_2d[row,col].I recommend usually using the comma notation for clarity/

In [58]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))

# show 
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [59]:
arr_2d.shape

(3, 3)

In [60]:
arr_2d[1]

array([20, 25, 30])

In [61]:
arr_2d[2]

array([35, 40, 45])

In [62]:
# indexing teh specific value
# Format is arr_2d[row][col] or arr_2d[row,col]
#Getting individul element value

#arr_2d[row][col]


arr_2d[0][1]

10

In [63]:
#arr_2d{row,col}

arr_2d[0,2]

15

In [64]:
# 2D array slicing

#Shape (2,2)from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [65]:
arr_2d[1:3,:2]

array([[20, 25],
       [35, 40]])

In [66]:
arr_2d[2,:]

array([35, 40, 45])

# Fancy Indexing
Fancy indexing allows you to selct entire rows or columns out of order, to show this, let's quickly build out a numpy array

In [36]:
# set up matrix

array2d=np.zeros((10,10))
array2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
#length of array
arr_length=array2d.shape[1]
arr_length

10

In [41]:
#Set up array

for i in range(arr_length):
    array2d[i]=i
    
array2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [42]:
# Fancy indexing allows the following
array2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [44]:
#Allows in any order

array2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

# Selection 
Let's briefly go over how to use brackets for selection based off of comparison operators.

In [45]:
arr=np.arange(1,11)

In [46]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [49]:
#boolean datatype
arr>=4

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [51]:
bool_value=arr>=4
bool_value

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [52]:
arr[bool_value]

array([ 4,  5,  6,  7,  8,  9, 10])

In [56]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
x=3
arr[arr>x]

array([ 4,  5,  6,  7,  8,  9, 10])