In [3]:
import numpy as np

In [4]:
arr=np.arange(0,21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
arr[8]

8

In [6]:
arr[2:5]

array([2, 3, 4])

In [7]:
slice_of_arr=arr[1:5]
slice_of_arr

array([1, 2, 3, 4])

In [8]:
slice_of_arr[:]=2000
slice_of_arr

array([2000, 2000, 2000, 2000])

In [9]:
y=arr.copy()
y

array([   0, 2000, 2000, 2000, 2000,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20])

# Indexing

In [10]:
arr_ind=np.array(([2,3,4],[5,6,7],[8,9,10]))
arr_ind

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [11]:
arr_ind.shape

(3, 3)

In [12]:
arr_ind[2]

array([ 8,  9, 10])

In [13]:
arr_ind[1:3]

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [14]:
arr_ind[:1,:]

array([[2, 3, 4]])

In [15]:
arr_ind[1:2,1:3]

array([[6, 7]])

# Fancy Indexing Q1

In [16]:
array_2=np.zeros((3,3))
array_2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
array_2.shape

(3, 3)

In [18]:
arr_length=array_2.shape[1]
arr_length

3

In [19]:
for i in range(arr_length):
    array_2[i]=i
array_2

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.]])

In [20]:
array_2[[1,2,2]]

array([[1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [21]:
for i in range(0,3):
    array_2[i]=i
array_2

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.]])

In [22]:
arr=range(3)
arr

range(0, 3)

In [23]:
arry1=np.arange(0,3)
arry1

array([0, 1, 2])

# Fancy Index Q2

In [24]:
array2=np.zeros((5,5))
array2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
array2.shape

(5, 5)

In [91]:
arr_length2=array2.shape[1]
arr_length2

5

In [92]:
for i in range(arr_length2):
    array2[i]=i
array2  

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [28]:
array2[[2,2,1,1]]

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
arr2=range(5)
arr2

range(0, 5)

In [30]:
arr02=np.arange(0,5)
arr02

array([0, 1, 2, 3, 4])

In [85]:
for i in range(0,5):
    array2[i]=i
array2

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

# Fancy Index Q3

In [79]:
array_3=np.zeros((4,4))
array_3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
array_3.shape

(4, 4)

In [81]:
arr_length3=array_3.shape[1]
arr_length3

4

In [83]:
for i in range(arr_length3):
    array_3[i]=i
array_3

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [84]:
array_3=np.arange(0,4)
array_3

array([0, 1, 2, 3])

# Selection

In [37]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr>9

array([False, False, False, False, False, False, False, False, False,
        True])

In [39]:
bool_value=arr>3
bool_value

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [40]:
arr[bool_value]

array([ 4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
x=4
arr[arr>x]

array([ 5,  6,  7,  8,  9, 10])

# Practice

In [67]:
np.arange(51)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [69]:
arr1=np.arange(0,20,5)
arr1

array([ 0,  5, 10, 15])

In [70]:
arr1.reshape(2,2)

array([[ 0,  5],
       [10, 15]])

In [73]:
array1=np.zeros((6,6))
array1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [74]:
array1.shape

(6, 6)

In [77]:
arr_length=array1.shape[1]
arr_length

6

In [78]:
for i in range(arr_length):
    array1[i]=i
array1

array([[0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5.]])

In [97]:
arr=np.arange(41)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40])

In [112]:
arr2=arr[1:41]
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [114]:
arr_shape=arr2.reshape(5,8)
arr_shape

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40]])

In [115]:
arr_shape.shape

(5, 8)

In [117]:
arr2.min()

1

In [118]:
arr2.max()

40

In [119]:
arr2.dtype

dtype('int32')